flatpaks = [
    # my usual
    "com.github.tchx84.Flatseal",
    "org.gimp.GIMP",
    "com.spotify.Client",
    "com.discordapp.Discord",
    "com.vivaldi.Vivaldi",
    "org.mozilla.firefox",
    "org.ferdium.Ferdium",
    "org.signal.Signal",
    # "org.zotero.Zotero",
    "org.videolan.VLC",
    "org.libreoffice.LibreOffice",
    # gnome specific
    # "org.gnome.Calendar",
    "org.gnome.Connections",
    "org.gnome.baobab",
    "org.gnome.font-viewer",
    "org.gnome.Snapshot",
    # "org.gnome.Calendar",
    "org.gnome.NautilusPreviewer",
    "org.gnome.Loupe",
    "org.gnome.Calculator",
    "org.gnome.Evince",
    # "org.gnome.Contacts",
    # "org.gnome.Weather",
    "org.gnome.Maps",
    "org.gnome.TextEditor",
    "org.gnome.Characters",
    "org.gnome.Logs",
    "org.gnome.clocks",
    "org.gnome.Extensions",
    # "com.hunterwittenborn.Celeste",
    # misc?
    "org.fedoraproject.MediaWriter",
]
